ignore-path: .gitignore

ignores:
  # used in a jsdoc type
  - '@typescript-eslint/utils'
  # used in __fixtures__/registry.ts by partial name
  - verdaccio-auth-memory
  - verdaccio-memory
  # ok with using implicit dev dep for now (part of verdaccio)
  - '@verdaccio/config'
  # needed for type references from verdaccio (not listed in deps)
  - '@verdaccio/types'
  # not detected under .vuepress? or implicit peers?
  - '@vuepress/*'
  - mermaid
  - sass-embedded
  # not detected in script
  - cross-env
