ignore-path: .gitignore

ignores:
  # used in a jsdoc type
  - '@typescript-eslint/utils'
  # used in __fixtures__/registry.ts by partial name
  - verdaccio-auth-memory
  - verdaccio-memory
  # ok with using implicit dev dep for now (part of verdaccio)
  - '@verdaccio/config'

ignore-patterns:
  # managed separately
  - docs
