enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

plugins:
  - checksum: aa1ed0aae31c7c0ad28cbb0c216678121d57f3db91ce31ee470a2f4b8064ebe90bc678e1ed7d0e3a640307bd16e5024a1885e3c56e9978a1935a7c46191fe27b
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/microsoft/beachball/yarn-plugin-engines_v0.3.1/yarn-plugins/engines/dist/plugin.js'
  # This is enabled (YARN_NPMRC_AUTH_ENABLED) only for ADO publish by .ado/release.yml
  - checksum: 5ea21341a477907c298afb531f4a0b30f4347e893a3dc9b72c74645a38bb99e760ba8eca5bf1f13cc36d0cdf4ee208df7d96229e54bf604222b3151e5b2b0565
    path: .yarn/plugins/@yarnpkg/plugin-npmrc.cjs
    spec: 'https://raw.githubusercontent.com/microsoft/beachball/yarn-plugin-npmrc_v0.5.1/yarn-plugins/npmrc/dist/plugin.js'

preferReuse: true

yarnPath: .yarn/releases/yarn-4.18.0.cjs
