enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - lage
  - workspace-tools

# This plugin simplifies auth for the release pipeline by reusing .npmrc.
# It's enabled (npmrcAuthEnabled) only for ADO publish by preparePublishRegistry.ts.
# https://github.com/ecraig12345/yarn-plugins/tree/main/plugins/npmrc
plugins:
  - checksum: 5b951fd12049365fda51bcb29b3180394c117af5176ad5fe7da02eda91f1a412eabf3f53a4601394f1d27061dbf97072a280a53b859af5826067217eb671f0f2
    path: .yarn/plugins/@yarnpkg/plugin-npmrc.cjs
    spec: 'https://raw.githubusercontent.com/ecraig12345/yarn-plugins/npmrc_v0.3.4/plugins/npmrc/dist/plugin.js'

preferReuse: true

yarnPath: .yarn/releases/yarn-4.14.1.cjs
