import path from 'path';
import { filterIgnoredFiles } from '../monorepo/filterIgnoredFiles';
import type { BeachballOptions } from '../types/BeachballOptions';
import type { PackageInfo, PackageInfos, ScopedPackages } from '../types/PackageInfo';
import { getIncludedLoggers, isPackageIncluded } from './isPackageIncluded';

const count = (n: number, str: string) => `${n} ${str}${n === 1 ? '' : 's'}`;

/**
 * Gets all the changed package names, regardless of the change files.
 *
 * PRE: Assumes shared git history has already been fetched, probably by `getChangedPackages`.
 */
export function getAllChangedPackages(params: {
  options: Pick<BeachballOptions, 'path' | 'changeDir' | 'ignorePatterns' | 'verbose'>;
  packageInfos: PackageInfos;
  scopedPackages: ScopedPackages;
  /**
   * Paths of all committed and staged files in the current branch as returned by git,
   * relative to `options.path` with forward slashes.
   */
  allChangedFiles: Set<string>;
}): string[] {
  const { options, packageInfos, scopedPackages, allChangedFiles } = params;
  const { path: cwd, changeDir } = options;
  const { verboseLog, logIgnored, logIncluded } = getIncludedLoggers(options);

  if (!allChangedFiles.size) {
    verboseLog('Found no changed files in current branch');
    return [];
  }

  verboseLog(`Found ${count(allChangedFiles.size, 'changed file')} in current branch (before filtering)`);

  // Filter out changed files which are ignored by ignorePatterns.
  // Also ignore the CHANGELOG files and change files because they're generated by beachball.
  const nonIgnoredChanges = filterIgnoredFiles({
    filePaths: allChangedFiles,
    ignorePatterns: [...(options.ignorePatterns || []), `${changeDir}/*.json`, 'CHANGELOG.{md,json}'],
    logIgnored,
  });

  if (!nonIgnoredChanges.length) {
    verboseLog('All files were ignored');
    return [];
  }

  // Determine which package each changed file came from (using packageInfos[x].packageJsonPath),
  // and whether that package is in scope and not private
  const includedPackages = new Set<string>();
  let fileCount = 0;
  const packageInfosByPath: { [packageAbsNormalizedPath: string]: PackageInfo } = {};
  for (const info of Object.values(packageInfos)) {
    packageInfosByPath[path.normalize(path.dirname(info.packageJsonPath))] = info;
  }
  for (const moddedFile of nonIgnoredChanges) {
    const packageInfo = getMatchingPackageInfo(moddedFile, cwd, packageInfosByPath);
    if (!packageInfo) {
      logIgnored(moddedFile, 'not in a package');
      continue;
    }

    const { isIncluded, reason } = isPackageIncluded(packageInfo, scopedPackages);

    if (!isIncluded) {
      logIgnored(moddedFile, reason);
    } else {
      includedPackages.add(packageInfo.name);
      fileCount++;
      logIncluded(moddedFile);
    }
  }

  verboseLog(
    `Found ${count(fileCount, 'file')} in ${count(includedPackages.size, 'package')} that should be published`
  );

  return [...includedPackages];
}

function getMatchingPackageInfo(
  file: string,
  cwd: string,
  packageInfosByPath: { [packageAbsNormalizedPath: string]: PackageInfo }
): PackageInfo | undefined {
  // Normalize all the paths before comparing (the packageInfosByPath entries should also be normalized)
  // to ensure that this doesn't break on Windows if any input paths have forward slashes
  cwd = path.normalize(cwd);
  const absFile = path.normalize(path.join(cwd, file));
  let absDir = '';

  do {
    absDir = path.dirname(absDir || absFile);
    if (packageInfosByPath[absDir]) {
      return packageInfosByPath[absDir];
    }
  } while (absDir !== cwd);

  return undefined;
}
