import { ChangeFileInfo } from '../types/ChangeInfo';
import { findPackageRoot, getChangePath } from '../paths';
import { getChanges, getStagedChanges, git, fetchRemote, parseRemoteBranch } from '../git';
import fs from 'fs-extra';
import path from 'path';
import { getScopedPackages } from '../monorepo/getScopedPackages';
import { BeachballOptions } from '../types/BeachballOptions';

/**
 * Gets all the changed packages, regardless of the change files
 */
function getAllChangedPackages(options: BeachballOptions) {
  const { branch, path: cwd } = options;

  const changes = [...(getChanges(branch, cwd) || []), ...(getStagedChanges(branch, cwd) || [])];
  const scopedPackages = getScopedPackages(options);
  const ignoredFiles = ['CHANGELOG.md', 'CHANGELOG.json'];
  const packageRoots: { [pathName: string]: string } = {};
  if (changes) {
    // Discover package roots from modded files (ignores the CHANGELOG file because that's generated by beachball)
    changes
      .filter(name => !ignoredFiles.includes(path.basename(name)))
      .forEach(moddedFile => {
        const root = findPackageRoot(path.join(cwd, path.dirname(moddedFile)));

        if (root && !packageRoots[root]) {
          try {
            const packageJson = fs.readJSONSync(path.join(root, 'package.json'));

            if (!packageJson.private && (!packageJson.beachball || packageJson.beachball.shouldPublish !== false)) {
              const packageName = packageJson.name;

              if (scopedPackages.includes(packageName)) {
                packageRoots[root] = packageName;
              }
            }
          } catch (e) {
            // Ignore JSON errors
          }
        }
      });
  }

  return Object.values(packageRoots);
}

/**
 * Gets all the changed packages, accounting for change files
 */
export function getChangedPackages(options: BeachballOptions) {
  const { fetch, path: cwd, branch } = options;

  const changePath = getChangePath(cwd);

  if (fetch) {
    const { remote, remoteBranch } = parseRemoteBranch(branch);
    console.log(`fetching latest from remotes "${remote}/${remoteBranch}"`);
    fetchRemote(remote, remoteBranch, cwd);
  }

  const changedPackages = getAllChangedPackages(options);

  const changeFilesResult = git(['diff', '--name-only', '--no-renames', '--diff-filter=A', `${branch}...`], { cwd });

  if (!changePath || !fs.existsSync(changePath) || !changeFilesResult.success) {
    return changedPackages;
  }

  const changes = changeFilesResult.stdout.split(/\n/);
  const changeFiles = changes.filter(name => path.dirname(name) === 'change');
  const changeFilePackageSet = new Set<string>();

  // Loop through the change files, building up a set of packages that we can skip
  changeFiles.forEach(file => {
    try {
      const changeInfo: ChangeFileInfo = fs.readJSONSync(file);
      changeFilePackageSet.add(changeInfo.packageName);
    } catch (e) {
      console.warn(`Invalid change file encountered: ${file}`);
    }
  });

  if (changeFilePackageSet.size > 0) {
    console.log(
      'Your local repository already has change files for these packages:' +
        [...changeFilePackageSet]
          .sort()
          .map(pkg => `\n  ${pkg}`)
          .join('')
    );
  }

  return changedPackages.filter(pkgName => !changeFilePackageSet.has(pkgName));
}
