// based on the non-worker part of https://github.com/microsoft/vscode/blob/main/build/azure-pipelines/common/publish.ts
// called by https://github.com/microsoft/vscode/blob/main/build/azure-pipelines/product-publish.yml#L106

import fs from 'fs';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import type { ReadableStream } from 'node:stream/web';
import { Worker } from 'node:worker_threads';
import path from 'path';
import yauzl from 'yauzl';
import type { ESRPReleaseWorkerData, ReleaseType } from './types.ts';
import { getAadToken } from './utils/getAadToken.ts';
import { getEnv } from './utils/getEnv.ts';
import { retry } from './utils/retry.ts';
import { createLog } from './utils/createLog.ts';
import { createStaticLinkReleaseRequest } from './releaseRequests/staticLinkRelease.ts';

// NOTE: GUIDs generated by this function aren't used
const vscodeRequestBase = createStaticLinkReleaseRequest({
  driEmail: ['example@microsoft.com'],
  createdBy: 'example@microsoft.com',
  owners: ['example@microsoft.com'],
  approvers: ['example@microsoft.com'],
  releaseTitle: 'VS Code',
  releaseContentType: 'InstallPackage',
  productInfo: { name: 'VS Code', description: 'VS Code' },
  accessPermissionsInfo: {
    mainPublisher: 'VSCode',
    allDownloadEntities: ['VSCode'],
  },
  // filled in later
  files: [],
});
const baseReleaseRequest = vscodeRequestBase;
const releaseType: ReleaseType = 'staticLink';
const containerName = 'staging';
// vscode which has multiple build "quality" variants (e.g. "insiders) does {quality}/{version}
const friendlyFileNamePrefix = undefined;
// vscode: /^vscode_(?<product>[^_]+)_(?<os>[^_]+)(?:_legacy)?_(?<arch>[^_]+)_(?<unprocessedType>[^_]+)$/
const validArtifactNameRegexp = /./;

const env = {
  buildsApiUrl: getEnv('BUILDS_API_URL'),
  prssCdnUrl: getEnv('PRSS_CDN_URL'),
  releaseTenantId: getEnv('RELEASE_TENANT_ID'),
  releaseClientId: getEnv('RELEASE_CLIENT_ID'),
  releaseAuthCert: getEnv('RELEASE_AUTH_CERT'),
  releaseRequestSigningCert: getEnv('RELEASE_REQUEST_SIGNING_CERT'),
  vscodeBuildStageWindows: getEnv('VSCODE_BUILD_STAGE_WINDOWS'), // True|False
  vscodeQuality: getEnv('VSCODE_QUALITY'),
  stagingStorageAccountName: getEnv('VSCODE_STAGING_BLOB_STORAGE_ACCOUNT_NAME'),
  authCertificatePfx: getEnv('RELEASE_AUTH_CERT'),
  requestSigningCertificatePfx: getEnv('RELEASE_REQUEST_SIGNING_CERT'),
  azureTenantId: getEnv('AZURE_TENANT_ID'),
  azureClientId: getEnv('AZURE_CLIENT_ID'),
  azureIdToken: getEnv('AZURE_ID_TOKEN'),

  // ADO
  buildSourceVersion: getEnv('BUILD_SOURCEVERSION'),
  // Pipeline.Workspace is the same as Agent.BuildDirectory
  pipelineWorkspacePath: getEnv('PIPELINE_WORKSPACE'),
  stageAttempt: getEnv('SYSTEM_STAGEATTEMPT'),
  systemAccessToken: getEnv('SYSTEM_ACCESSTOKEN'),
  agentTempDirectory: getEnv('AGENT_TEMPDIRECTORY'),
};

interface Artifact {
  name: string;
  resource: {
    downloadUrl: string;
    properties: {
      artifactsize: number;
    };
  };
}

class State {
  private statePath: string;
  private set = new Set<string>();

  constructor() {
    const previousState = fs
      .readdirSync(env.pipelineWorkspacePath)
      .map(name => /^artifacts_processed_(\d+)$/.exec(name))
      .filter((match): match is RegExpExecArray => !!match)
      .map(match => ({ name: match[0], attempt: Number(match[1]) }))
      .sort((a, b) => b.attempt - a.attempt)[0];

    if (previousState) {
      const previousStatePath = path.join(env.pipelineWorkspacePath, previousState.name, previousState.name + '.txt');
      fs.readFileSync(previousStatePath, 'utf8')
        .split(/\n/)
        .filter(name => !!name)
        .forEach(name => this.set.add(name));
    }

    this.statePath = path.join(
      env.pipelineWorkspacePath,
      `artifacts_processed_${env.stageAttempt}`,
      `artifacts_processed_${env.stageAttempt}.txt`
    );
    fs.mkdirSync(path.dirname(this.statePath), { recursive: true });
    fs.writeFileSync(this.statePath, [...this.set.values()].map(name => `${name}\n`).join(''));
  }

  get size(): number {
    return this.set.size;
  }

  has(name: string): boolean {
    return this.set.has(name);
  }

  add(name: string): void {
    this.set.add(name);
    fs.appendFileSync(this.statePath, `${name}\n`);
  }

  [Symbol.iterator](): IterableIterator<string> {
    return this.set[Symbol.iterator]();
  }
}

const azdoFetchOptions = {
  headers: {
    // Pretend we're a web browser to avoid download rate limits
    'User-Agent':
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0',
    Accept:
      'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
    Referer: 'https://dev.azure.com',
    Authorization: `Bearer ${env.systemAccessToken}`,
  },
};

async function requestAZDOAPI<T>(apiPath: string): Promise<T> {
  const abortController = new AbortController();
  const timeout = setTimeout(() => abortController.abort(), 2 * 60 * 1000);

  try {
    const res = await retry(() =>
      fetch(`${env.buildsApiUrl}${apiPath}?api-version=6.0`, {
        ...azdoFetchOptions,
        signal: abortController.signal,
      })
    );

    if (!res.ok) {
      throw new Error(`Unexpected status code: ${res.status}`);
    }

    return (await res.json()) as T;
  } finally {
    clearTimeout(timeout);
  }
}

async function getPipelineArtifacts(): Promise<Artifact[]> {
  const result = await requestAZDOAPI<{ readonly value: Artifact[] }>('artifacts');
  return result.value.filter(a => /^vscode_/.test(a.name) && !/sbom$/.test(a.name));
}

interface Timeline {
  readonly records: {
    readonly name: string;
    readonly type: string;
    readonly state: string;
    readonly result: string;
  }[];
}

async function getPipelineTimeline(): Promise<Timeline> {
  return await requestAZDOAPI<Timeline>('timeline');
}

async function downloadArtifact(artifact: Artifact, downloadPath: string): Promise<void> {
  const abortController = new AbortController();
  const timeout = setTimeout(() => abortController.abort(), 4 * 60 * 1000);

  try {
    const res = await fetch(artifact.resource.downloadUrl, {
      ...azdoFetchOptions,
      signal: abortController.signal,
    });

    if (!res.ok) {
      throw new Error(`Unexpected status code: ${res.status}`);
    }

    await pipeline(Readable.fromWeb(res.body as ReadableStream), fs.createWriteStream(downloadPath));
  } finally {
    clearTimeout(timeout);
  }
}

async function unzip(packagePath: string, outputPath: string): Promise<string[]> {
  return new Promise((resolve, reject) => {
    yauzl.open(packagePath, { lazyEntries: true, autoClose: true }, (err, zipfile) => {
      if (err) {
        return reject(err);
      }

      const result: string[] = [];
      zipfile.on('entry', (entry: yauzl.Entry) => {
        if (entry.fileName.endsWith('/')) {
          zipfile.readEntry();
        } else {
          zipfile.openReadStream(entry, (err2, istream) => {
            if (err2) return reject(err2);

            const filePath = path.join(outputPath, entry.fileName);
            fs.mkdirSync(path.dirname(filePath), { recursive: true });

            const ostream = fs.createWriteStream(filePath);
            ostream.on('finish', () => {
              result.push(filePath);
              zipfile.readEntry();
            });
            istream?.on('error', err3 => reject(err3));
            istream.pipe(ostream);
          });
        }
      });

      zipfile.on('close', () => resolve(result));
      zipfile.readEntry();
    });
  });
}

// It is VERY important that we don't download artifacts too much too fast from AZDO.
// AZDO throttles us SEVERELY if we do. Not just that, but they also close open
// sockets, so the whole things turns to a grinding halt. So, downloading and extracting
// happens serially in the main thread, making the downloads are spaced out
// properly. For each extracted artifact, we spawn a worker thread to upload it to
// the CDN and finally update the build in Cosmos DB.
async function main() {
  const done = new State();
  const processing = new Set<string>();

  for (const name of done) {
    console.log(`\u2705 ${name}`);
  }

  // TODO determine if needed and replace
  const stages = new Set<string>(['Quality']);
  if (env.vscodeBuildStageWindows === 'True') {
    stages.add('Windows');
  }

  // In the vscode example, the pipeline acquires this token in a previous step and stores it in
  // PUBLISH_AUTH_TOKENS env, but that appears to only be necessary since multiple steps need the token
  const publishAuthToken = await getAadToken({
    endpoint: `https://${env.stagingStorageAccountName}.blob.core.windows.net/`,
    tenantId: env.azureTenantId,
    clientId: env.azureClientId,
    auth: { idToken: env.azureIdToken },
  });

  let timeline: Timeline;
  let artifacts: Artifact[];
  let resultPromise = Promise.resolve<PromiseSettledResult<void>[]>([]);
  const operations: { name: string; operation: Promise<void> }[] = [];

  while (true) {
    [timeline, artifacts] = await Promise.all([
      retry(() => getPipelineTimeline()),
      retry(() => getPipelineArtifacts()),
    ]);
    const stagesCompleted = new Set<string>(
      timeline.records.filter(r => r.type === 'Stage' && r.state === 'completed' && stages.has(r.name)).map(r => r.name)
    );
    const stagesInProgress = [...stages].filter(s => !stagesCompleted.has(s));
    const artifactsInProgress = artifacts.filter(a => processing.has(a.name));

    if (stagesInProgress.length === 0 && artifacts.length === done.size + processing.size) {
      break;
    } else if (stagesInProgress.length > 0) {
      console.log('Stages in progress:', stagesInProgress.join(', '));
    } else if (artifactsInProgress.length > 0) {
      console.log('Artifacts in progress:', artifactsInProgress.map(a => a.name).join(', '));
    } else {
      console.log(`Waiting for a total of ${artifacts.length}, ${done.size} done, ${processing.size} in progress...`);
    }

    for (const artifact of artifacts) {
      if (done.has(artifact.name) || processing.has(artifact.name)) {
        continue;
      }

      const artifactLog = createLog(artifact.name);
      artifactLog(`Found new artifact`);

      const artifactZipPath = path.join(env.agentTempDirectory, `${artifact.name}.zip`);

      await retry(async attempt => {
        const start = Date.now();
        artifactLog(`Downloading (attempt ${attempt})...`);
        await downloadArtifact(artifact, artifactZipPath);
        const archiveSize = fs.statSync(artifactZipPath).size;
        const downloadDurationS = (Date.now() - start) / 1000;
        const downloadSpeedKBS = Math.round(archiveSize / 1024 / downloadDurationS);
        artifactLog(
          `Successfully downloaded after ${Math.floor(downloadDurationS)} seconds(${downloadSpeedKBS} KB/s).`
        );
      });

      const artifactFilePaths = await unzip(artifactZipPath, env.agentTempDirectory);
      const artifactFilePath = artifactFilePaths.filter(p => !/_manifest/.test(p))[0];

      processing.add(artifact.name);
      const promise = new Promise<void>((resolve, reject) => {
        if (!validArtifactNameRegexp.test(artifact.name)) {
          reject(new Error(`Invalid artifact name: ${artifact.name}`));
          return;
        }

        const worker = new Worker(path.join(import.meta.dirname, 'worker.ts'), {
          workerData: {
            artifactName: artifact.name,
            artifactFilePath,
            publishAuthToken,
            authCertificatePfx: env.authCertificatePfx,
            requestSigningCertificatePfx: env.requestSigningCertificatePfx,
            clientId: env.releaseClientId,
            storageAccountName: env.stagingStorageAccountName,
            containerName,
            tenantId: env.releaseTenantId,
            version: env.buildSourceVersion,
            releaseType,
            baseReleaseRequest,
            friendlyFileNamePrefix,
          } satisfies ESRPReleaseWorkerData,
        });
        worker.on('error', reject);
        worker.on('exit', code => {
          if (code === 0) {
            resolve();
          } else {
            reject(new Error(`[${artifact.name}] Worker stopped with exit code ${code}`));
          }
        });
      });

      const operation = promise.then(() => {
        processing.delete(artifact.name);
        done.add(artifact.name);
        console.log(`\u2705 ${artifact.name} `);
      });

      operations.push({ name: artifact.name, operation });
      resultPromise = Promise.allSettled(operations.map(o => o.operation));
    }

    await new Promise(c => setTimeout(c, 10_000));
  }

  console.log(
    `Found all ${done.size + processing.size} artifacts, waiting for ${processing.size} artifacts to finish publishing...`
  );

  const artifactsInProgress = operations.filter(o => processing.has(o.name));

  if (artifactsInProgress.length > 0) {
    console.log('Artifacts in progress:', artifactsInProgress.map(a => a.name).join(', '));
  }

  const results = await resultPromise;

  for (let i = 0; i < operations.length; i++) {
    const result = results[i];

    if (result.status === 'rejected') {
      console.error(`[${operations[i].name}]`, result.reason);
    }
  }

  // Fail the job if any of the artifacts failed to publish
  if (results.some(r => r.status === 'rejected')) {
    throw new Error('Some artifacts failed to publish');
  }

  // Also fail the job if any of the stages did not succeed
  let shouldFail = false;

  for (const stage of stages) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const record = timeline.records.find(r => r.name === stage && r.type === 'Stage')!;

    if (record.result !== 'succeeded' && record.result !== 'succeededWithIssues') {
      shouldFail = true;
      console.error(`Stage ${stage} did not succeed: ${record.result}`);
    }
  }

  if (shouldFail) {
    throw new Error('Some stages did not succeed');
  }

  console.log(`All ${done.size} artifacts published!`);
}

await main().catch(err => {
  console.error((err as Error).stack || err);
  // eslint-disable-next-line no-restricted-properties
  process.exit(1);
});
