name: Install Beachball
description: Globally installs Beachball version specified in the repo root package.json devDependencies, or latest
runs:
  using: composite
  steps:
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
      with:
        script: |
          const beachballVersion = require('./package.json').devDependencies.beachball || 'latest';
          console.log(`Using beachball@${beachballVersion}...`)
          await exec.exec('npm', ['i', '-g', `beachball@${beachballVersion}`]);
