ignore-path: ../../.gitignore

ignores:
  # used in registry.ts by name
  - verdaccio
  - verdaccio-auth-memory
  - verdaccio-memory
  # specified at root
  - '@jest/globals'
  # needed for type references from verdaccio
  - '@verdaccio/types'
  # needed for type references from @verdaccio/types
  - '@types/jsonwebtoken'
