# The release pipeline to publish NPM packages to npmjs.com via ESRP ("beachball - release")
# Based on https://github.com/microsoft/node-api-dotnet/blob/main/.ado/release.yml

# Name of the run
# NOTE: this is referenced in packages/beachball/src/env.ts as BUILD_BUILDNUMBER for some tests
name: beachball-release-$(Date:yyyy-MM-dd).$(Rev:rr)

trigger: none

resources:
  pipelines:
    # must match publishPipelineAlias variable
    - pipeline: prepublish
      project: ISS
      source: beachball - prepublish
      trigger:
        branches:
          include:
            - main
            - user/elcraig/1es-pt-migration-publish

  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

variables:
  nodeVersion: 24
  publishPipelineAlias: prepublish
  packagesArtifactName: packed-packages
  releaseApiToolArtifactName: release-api-tool

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      vmImage: windows-latest
      os: windows

    stages:
      - stage: main_release
        displayName: Publish packages
        jobs:
          - job: npm_release
            displayName: NPM to npmjs.com
            templateContext:
              type: releaseJob
              isProduction: true
              inputs:
                - input: pipelineArtifact
                  pipeline: ${{ variables.publishPipelineAlias }}
                  artifactName: ${{ variables.packagesArtifactName }}
                  targetPath: $(Agent.BuildDirectory)\${{ variables.packagesArtifactName }}
                - input: pipelineArtifact
                  pipeline: ${{ variables.publishPipelineAlias }}
                  artifactName: ${{ variables.releaseApiToolArtifactName }}
                  targetPath: $(Agent.BuildDirectory)\${{ variables.releaseApiToolArtifactName }}

            # Use ESRP Release to securely publish to npmjs.com.
            steps:
              - task: UseNode@1
                displayName: Install Node.js ${{ variables.nodeVersion }}
                retryCountOnTaskFailure: 1
                inputs:
                  version: '${{ variables.nodeVersion }}.x'
                  checkLatest: false

              - script: dir /S $(Agent.BuildDirectory)\${{ variables.packagesArtifactName }}
                displayName: Show directory contents

              # Get credentials that will be used to temporarily upload zips to ogxesrptempstorage
              # in the OGX azure subscription
              - task: AzureCLI@2
                displayName: Get credentials for staging blob storage
                inputs:
                  # this is the service connection name
                  azureSubscription: Office-ogx-esrp-infra-bot
                  scriptType: pscore
                  scriptLocation: inlineScript
                  addSpnToEnvironment: true
                  inlineScript: |
                    Write-Host "##vso[task.setvariable variable=STAGING_TENANT_ID]$env:tenantId"
                    Write-Host "##vso[task.setvariable variable=STAGING_CLIENT_ID]$env:servicePrincipalId"
                    Write-Host "##vso[task.setvariable variable=STAGING_ID_TOKEN;issecret=true]$env:idToken"

              # Fetch ESRP certificates from key vault in Torus
              - task: AzureKeyVault@2
                displayName: Get ESRP certificates from Key Vault
                inputs:
                  # torus service connection name ("connectedservicename" from EsrpRelease task)
                  azureSubscription: ESRP-JSHost3
                  # "keyvaultname" from EsrpRelease task
                  KeyVaultName: OGX-JSHost-KV
                  # "authcertname" and "signcertname" from EsrpRelease task
                  SecretsFilter: OGX-JSHost-Auth4,OGX-JSHost-Sign3

              - script: node $(Agent.BuildDirectory)\${{ variables.releaseApiToolArtifactName }}\index.js
                displayName: Publish to npmjs.com using ESRP Release API wrapper
                retryCountOnTaskFailure: 3
                env:
                  PACKED_PACKAGES_PATH: $(Agent.BuildDirectory)\${{ variables.packagesArtifactName }}
                  ESRP_PRODUCT_NAME: beachball
                  ESRP_NPM_TAG: test
                  ESRP_USER: elcraig@microsoft.com
                  ESRP_APPROVERS: dannyvv@microsoft.com
                  # torus tenant ID ("domaintenantid" from EsrpRelease task, same as service connection "ESRP-JSHost3")
                  ESRP_TENANT_ID: cdc5aeea-15c5-4db6-b079-fcadd2505dc2
                  # "clientid" from EsrpRelease task
                  ESRP_CLIENT_ID: 0a35e01f-eadf-420a-a2bf-def002ba898d
                  ESRP_AUTH_CERT: $(OGX-JSHost-Auth4)
                  ESRP_REQUEST_SIGNING_CERT: $(OGX-JSHost-Sign3)
                  STAGING_STORAGE_ACCOUNT_NAME: ogxesrptempstorage
                  STAGING_CLIENT_ID: $(STAGING_CLIENT_ID)
                  STAGING_TENANT_ID: $(STAGING_TENANT_ID)
                  STAGING_ID_TOKEN: $(STAGING_ID_TOKEN)
