# Pipeline: "beachball - release"
# The release pipeline to build, test, and pack NPM packages, publish them via ESRP,
# and push the resulting changes back to git.
#
# References:
# https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/overview
# https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/migration/office-specific-guidance
# https://github.com/microsoft/node-api-dotnet/blob/main/.ado/publish.yml
# https://github.com/microsoft/fluentui/blob/master/azure-pipelines.release.yml
#
#
# NOTE: ESRP release should probably be in a job with `type: releaseJob`. This applies stricter
# network isolation policies to the entire pipeline by default, which are overridden below so the
# build/push steps work. This isn't ideal, but the current design of a git push stage which runs
# after the ESRP release stage would require three separate pipelines. (In theory it's possible to
# trigger an ESRP pipeline on build stage completion, then have a later stage here wait for its
# completion before pushing back to git, but that setup hits a MOBR global-build-success-validation
# gate on the release pipeline, since the whole pipeline the artifact comes from hasn't succeeded yet.)

# Name of the run
# NOTE: this is referenced in packages/beachball/src/env.ts as BUILD_BUILDNUMBER for some tests
name: beachball-release-$(Date:yyyy-MM-dd).$(Rev:rr)

# This script must never be triggered from YAML settings for security reasons.
pr: none
trigger: none

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

# Temporary workaround to publish two groups of packages with different versioning strategies
# TODO (release): go back to a single publish step
parameters:
  - name: npmPublishes
    type: object
    default:
      - groupName: canary
        artifactPathVariable: canaryArtifactPath
        npmTag: next
      - groupName: others
        artifactPathVariable: packagesArtifactPath
        npmTag: latest

variables:
  nodeVersion: 24
  tags: production
  # Single artifact containing all subfolders below (to consolidate compliance auto validation)
  artifactName: release-artifacts
  packagesDirName: packed-packages
  # TODO (release): remove all canary artifacts
  canaryDirName: packed-packages-canary
  toolDirName: release-api-tool

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      # the auto-injected SDL source-analysis (Guardian) stage is Windows-only
      image: windows-latest
      os: windows
    featureFlags:
      incrementalSDLSourceAnalysis: true
    sdl:
      codeql:
        runSourceLanguagesInSourceAnalysis: true
    settings:
      # If any job has `type: releaseJob`, it applies strict network isolation to the whole pipeline.
      # Re-enable the access needed.
      networkIsolationPolicy: AzureActiveDirectory,AzureKeyVault,AzureResourceManager,AzureStorage,GitHub

    stages:
      - stage: build
        displayName: Build artifacts
        jobs:
          - job: build
            displayName: Build, test, pack

            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux

            workspace:
              clean: all

            variables:
              artifactPath: $(Build.StagingDirectory)/out
              packagesArtifactPath: $(artifactPath)/${{ variables.packagesDirName }}
              canaryArtifactPath: $(artifactPath)/${{ variables.canaryDirName }}
              toolArtifactPath: $(artifactPath)/${{ variables.toolDirName }}

            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: ${{ variables.artifactName }}
                  path: $(artifactPath)

            steps:
              - template: /.ado/templates/setup.yml@self

              - script: yarn build --verbose
                displayName: Build

              - script: yarn test --verbose
                displayName: Test

              - script: mkdir -p "$(canaryArtifactPath)" "$(packagesArtifactPath)"
                displayName: Create package artifact directories

              - script: yarn beachball:release canary --pack-to-path "$(canaryArtifactPath)"
                displayName: Pack packages (canary)

              - script: yarn beachball:release publish --no-push --pack-to-path "$(packagesArtifactPath)"
                displayName: Pack packages (others)

              - script: |
                  mkdir -p '$(toolArtifactPath)'
                  cp -r packages/esrp-npm-release/dist/index.mjs '$(toolArtifactPath)'
                displayName: Copy release API tool to staging directory

              - script: ls -R '$(artifactPath)'
                displayName: Show all output files

      - stage: publish
        displayName: Publish
        dependsOn: build
        jobs:
          - job: npm_publish
            displayName: Publish npm packages

            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux

            variables:
              artifactPath: $(Agent.BuildDirectory)/${{ variables.artifactName }}
              packagesArtifactPath: $(artifactPath)/${{ variables.packagesDirName }}
              canaryArtifactPath: $(artifactPath)/${{ variables.canaryDirName }}
              toolArtifactBin: $(artifactPath)/${{ variables.toolDirName }}/index.mjs

            templateContext:
              type: releaseJob
              isProduction: true
              inputs:
                - input: pipelineArtifact
                  artifactName: ${{ variables.artifactName }}
                  targetPath: $(artifactPath)

            steps:
              - task: UseNode@1
                displayName: Install Node.js ${{ variables.nodeVersion }}
                retryCountOnTaskFailure: 1
                inputs:
                  version: ${{ variables.nodeVersion }}.x
                  checkLatest: false

              - script: ls -R '$(artifactPath)'
                displayName: Show artifact contents

              # Get credentials that will be used to temporarily upload zips to ogxesrptempstorage
              # in the OGX azure subscription
              - task: AzureCLI@2
                displayName: Get credentials for staging blob storage
                inputs:
                  # this is the service connection name
                  azureSubscription: ogx-esrp-infra-bot
                  scriptType: bash
                  scriptLocation: inlineScript
                  addSpnToEnvironment: true
                  inlineScript: |
                    echo "##vso[task.setvariable variable=STAGING_TENANT_ID]$tenantId"
                    echo "##vso[task.setvariable variable=STAGING_CLIENT_ID]$servicePrincipalId"
                    echo "##vso[task.setvariable variable=STAGING_ID_TOKEN;issecret=true]$idToken"

              # Fetch ESRP certificates from key vault in Torus
              - task: AzureKeyVault@2
                displayName: Get ESRP certificates from Key Vault
                inputs:
                  # torus service connection name ("connectedservicename" from EsrpRelease task)
                  azureSubscription: ESRP-JSHost3
                  # "keyvaultname" from EsrpRelease task
                  KeyVaultName: OGX-JSHost-KV
                  # "authcertname" and "signcertname" from EsrpRelease task
                  SecretsFilter: OGX-JSHost-Auth4,OGX-JSHost-Sign3

              # Publish each set of packed packages under its npm dist-tag.
              # (Beachball doesn't really need ordered publishing, but we want to test the helper.)
              - ${{ each publish in parameters.npmPublishes }}:
                  - script: node "$(toolArtifactBin)"
                    displayName: '(${{ publish.groupName }}) npm publish using ESRP Release API'
                    retryCountOnTaskFailure: 3
                    env:
                      PACKED_PACKAGES_PATH: $(${{ publish.artifactPathVariable }})
                      # ideally would be "beachball" but isn't used anywhere meaningful
                      ESRP_PRODUCT_NAME: beachball-${{ publish.groupName }}
                      ESRP_NPM_TAG: ${{ publish.npmTag }}
                      ESRP_USER: elcraig@microsoft.com
                      ESRP_APPROVERS: dannyvv@microsoft.com
                      # torus tenant ID ("domaintenantid" from EsrpRelease task, same as service connection "ESRP-JSHost3")
                      ESRP_TENANT_ID: cdc5aeea-15c5-4db6-b079-fcadd2505dc2
                      # "clientid" from EsrpRelease task
                      ESRP_CLIENT_ID: 0a35e01f-eadf-420a-a2bf-def002ba898d
                      ESRP_AUTH_CERT: $(OGX-JSHost-Auth4)
                      ESRP_REQUEST_SIGNING_CERT: $(OGX-JSHost-Sign3)
                      STAGING_STORAGE_ACCOUNT_NAME: ogxesrptempstorage
                      STAGING_CLIENT_ID: $(STAGING_CLIENT_ID)
                      STAGING_TENANT_ID: $(STAGING_TENANT_ID)
                      STAGING_ID_TOKEN: $(STAGING_ID_TOKEN)

      # After a successful ESRP release, push the resulting changes (bumps, tags, changelogs) to git.
      - stage: push
        displayName: Push to git
        dependsOn: publish
        jobs:
          - job: push
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux
            steps:
              - template: /.ado/templates/setup.yml@self

              - task: AzureCLI@2
                displayName: Get token
                inputs:
                  azureSubscription: ogx-oss-release-bot
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: node scripts/create-github-app-token.cjs
                env:
                  # office-ogx-auth-helper GitHub App
                  APP_CLIENT_ID: Iv23ligBoU5jc9SIFnGR
                  KEY_ID: https://ogx-oss-release-keyvault.vault.azure.net/keys/office-ogx-auth-helper-key
                  REPOSITORIES: $(Build.Repository.ID)
                  PERMISSIONS: contents:write
                  OUTPUT: azure
                  AZURE_TOKEN_VARIABLE: GITHUB_APP_TOKEN

              # TODO (release): update task name
              - script: node scripts/publishWithGithubAppToken.ts
                displayName: Publish non-prerelease packages
                env:
                  GITHUB_APP_TOKEN: $(GITHUB_APP_TOKEN)
