name: Release

# Release on manual trigger only
on:
  workflow_dispatch:

# Use newer node and npm for trusted publishing support
env:
  npmVersion: 11
  nodeVersion: 22

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    # This environment contains secrets needed for publishing
    environment: release

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # Don't save creds in the git config (so it's easier to override later)
          persist-credentials: false

      - name: Install Node.js ${{ env.nodeVersion }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ env.nodeVersion }}

      - name: Install npm@${{ env.npmVersion }}
        run: npm install --global npm@${{ env.npmVersion }}

      - run: yarn --frozen-lockfile

      - run: yarn build

      - run: yarn test:unit

      - run: yarn test:func

      - name: yarn test:e2e (npm ${{ env.npmVersion }})
        run: yarn test:e2e

      - name: Publish package
        run: |
          git config user.email "kchau@microsoft.com"
          git config user.name "Ken Chau"

          # Get the existing remote URL without creds, and use a trap (like try/finally)
          # to restore it after this step finishes
          trap "git remote set-url origin '$(git remote get-url origin)'" EXIT

          # Add a token to the remote URL for auth during release
          git remote set-url origin "https://$REPO_PAT@github.com/$GITHUB_REPOSITORY"

          yarn release -y
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}
